Enhancement: Major rework
Script now passes shellcheck, and accepts specified cacert.

diff --git a/keytool-trust b/keytool-trust
--- a/keytool-trust
+++ b/keytool-trust
@@ -2,66 +2,50 @@
 # version 1.0
 # https://github.com/ssbarnea/keytool-trust
 REMHOST=$1
-REMPORT=${2:-443}
-
-KEYSTORE_PASS=changeit
-KEYTOOL="sudo keytool"
-
-# /etc/java-6-sun/security/cacerts
-
-for CACERTS in 	/usr/lib/jvm/java-8-oracle/jre/lib/security/cacerts \
-	/usr/lib/jvm/java-7-oracle/jre/lib/security/cacerts \
-	"/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/security/cacerts" \
-	"/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/MacOS/itms/java/lib/security/cacerts"
-do
-
-if [ -e "$CACERTS" ]
-then
-    echo --- Adding certs to $CACERTS
-
-# FYI: the default keystore is located in ~/.keystore
-
-if [ -z "$REMHOST" ]
-    then
+if [ -z "$REMHOST" ]; then
     echo "ERROR: Please specify the server name to import the certificatin from, eventually followed by the port number, if other than 443."
     exit 1
-    fi
-
-set -e
-
-rm -f $REMHOST:$REMPORT.pem
-
-if openssl s_client -connect $REMHOST:$REMPORT 1>/tmp/keytool_stdout 2>/tmp/output </dev/null
-        then
-        :
-        else
-        cat /tmp/keytool_stdout
-        cat /tmp/output
-        exit 1
-        fi
-
-if sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' </tmp/keytool_stdout > /tmp/$REMHOST:$REMPORT.pem
-        then
-        :
-        else
-        echo "ERROR: Unable to extract the certificate from $REMHOST:$REMPORT ($?)"
-        cat /tmp/output
-        fi
-
-if $KEYTOOL -list -storepass ${KEYSTORE_PASS} -alias $REMHOST:$REMPORT >/dev/null
-    then
-    echo "Key of $REMHOST already found, skipping it."
-    else
-    $KEYTOOL -import -trustcacerts -noprompt -storepass ${KEYSTORE_PASS} -alias $REMHOST:$REMPORT -file /tmp/$REMHOST:$REMPORT.pem
-    fi
-
-if $KEYTOOL -list -storepass ${KEYSTORE_PASS} -alias $REMHOST:$REMPORT -keystore "$CACERTS" >/dev/null
-    then
-    echo "Key of $REMHOST already found in cacerts, skipping it."
-    else
-    $KEYTOOL -import -trustcacerts -noprompt -keystore "$CACERTS" -storepass ${KEYSTORE_PASS} -alias $REMHOST:$REMPORT -file /tmp/$REMHOST:$REMPORT.pem
-    fi
-
 fi
 
+if [ -n "${3}" ]; then
+    declare -a CACERTS=("${3}")
+else
+    declare -a CACERTS=( \
+        "/usr/lib/jvm/java-8-oracle/jre/lib/security/cacerts" \
+        "/usr/lib/jvm/java-7-oracle/jre/lib/security/cacerts" \
+    )
+fi
+
+REMPORT=${2:-443}
+KEYSTORE_PASS=changeit
+KEYTOOL="$(which keytool)"
+TARGET="${REMHOST}:${REMPORT}"
+STDOUT="$(pwd)/$(basename "${0}").stdout"
+STDERR="$(pwd)/$(basename "${0}").stderr"
+for CACERT in "${CACERTS[@]}"; do
+    if [ ! -e "$CACERT" ]; then
+        echo "--- ${CACERT} not found!" 1>&2
+        continue
+    else
+        echo "--- Attempting to add cert of ${TARGET} to ${CACERT}"
+    fi
+
+    rm -f "${TARGET}.pem" "${STDOUT}" "${STDERR}"
+    if ! openssl s_client -connect "${TARGET}" 1>"${STDOUT}" 2>"${STDERR}" </dev/null; then
+        cat "${STDOUT}"
+        cat "${STDERR}"
+        continue
+    fi
+
+    if ! sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' <"${STDOUT}" > "$(pwd)/${TARGET}.pem"; then
+        echo "ERROR: Unable to extract the certificate from ${TARGET} ($?)"
+        cat "${STDERR}"
+	continue
+    fi
+
+    if $KEYTOOL -list -storepass ${KEYSTORE_PASS} -alias "${TARGET}" -keystore "$CACERT" >/dev/null; then
+        echo "Key of ${TARGET} already found in ${CACERT}, skipping it."
+    else
+        $KEYTOOL -import -trustcacerts -noprompt -keystore "$CACERT" -storepass ${KEYSTORE_PASS} -alias "${TARGET}" -file "${TARGET}.pem"
+    fi
 done
